### ISSUE TITLE
Hitting AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by StupacShakur82** [Akasireddy99/reddit-scraper-datacamp-tutorial#1]
when I copy the script directly, it runs until line 25 of the scraped page, where it then throws the following error:
Traceback (most recent call last):
  File "webscraper.py", line 19, in <module>
    author = post.find('a', class_="author").text
AttributeError: 'NoneType' object has no attribute 'text'

assuming it's just something that the script isn't accounting for.

**Comment by arkdev9** [comment]
You're right, the script isn't accounting for the fact that a user's account might have been deleted after uploading a post. That is what is happening in our case. We can get around this by assuming the poster has a deleted account if that function returns an AttributeError. The script has been fixed now.
